version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  api:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/SENG401BRUHDB
    volumes:
      - .:/app

volumes:
  mongodata:
    driver: local
