version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: SENG401BRUHDB
    volumes:
      - mongodata:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  api:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
     - MONGO_URI=mongodb://rootuser:rootpassword@mongodb:27017/SENG401BRUHDB?authSource=admin

    volumes:
      - .:/app

volumes:
  mongodata:
    driver: local
