version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    # Remove the ports mapping to prevent exposure to the host
    # ports:
    #   - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongodata:/data/db
    networks:
      - app-network  # Ensure it's on a specific network

  api:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"  # API is still exposed to the host if needed
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
    restart: unless-stopped
    networks:
      - app-network  # Ensure it's on the same network

volumes:
  mongodata:
    driver: local

networks:
  app-network:  # Define a custom network
    driver: bridge  # Optional; bridge is the default, but defining it explicitly is a good practice
